id = "one-darker"
name = "One Darker"
version = "1.0.0"
schema_version = 1
authors = ["Edney Osf <edney.osf@gmail.com>"]
description = "A darker variant of One Dark theme for Zed"
repository = "https://github.com/edneyosf/one-darker"
